name: docs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  routemaster: ^1.0.1
  flutter_quill: ^8.6.0
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/docs-logo.png
   - assets/images/g-logo-2.png
